### PR TITLE
Remove unused temp

### PR DESCRIPTION
**Pull request by mattwynne**

### CODE REVIEW

**Comment by mattwynne** [comment]
Just starting this PR for iterating on @bishboria's start on searching for usages of a temp.

Do we need a function like `#find_all` in NavigatesTrees?

**Comment by chrismdp** [comment]
We could follow capybara's lead and go with `all`, `find` (or `first`) and `count`.

Feels like we're moving toward a sexp-selector language, too. Hey ho.

**Comment by bishboria** [comment]
So I've got a solution that works for the method having the same name as the temp! Had to change the formatting for the expected output in the spec though...

**Comment by bishboria** [comment]
I've been having a think about the spec that is still pending on this branch: When the temp is the return value returns the original return value.

The only variants I can think of just now are:
    def meth
      fred = 35
    end

and:
    def meth
      fred = 35
      something_else
      fred
    end

This to me looks like InlineTemp...

Thoughts?

**Comment by mattwynne** [comment]
In both of those cases it's not unused, so I think the refactoring should throw an error saying it can't remove the temp because it's in use.

**Comment by bishboria** [comment]
@mattwynne @chrismdp @tooky @jimweirich @mocoso

Only one case to go now on remove unused temp (when the temp is the only thing in the method). Although I foresee a problem: There are a lot of changes going on in CLI that aren't present in the other branches, especially around raising errors...

This is likely to be a merging nightmare. Should we try to finish up the other branches first?

**Comment by chrismdp** [comment]
Feels like CLI is pretty much done for the moment... @mattwynne? I'm happy enough with it to merge in as stands, and make a future pull request for any mods.

**Comment by jimweirich** [comment]
On Jul 14, 2012, at 5:38 PM, Chris Parsons wrote:

> Feels like CLI is pretty much done for the moment... @mattwynne? I'm happy enough with it to merge in as stands, and make a future pull request for any mods.

For the record, I'm not a fan of long running branches.  Merge early, merge often.

## 

-- Jim Weirich
-- jim.weirich@gmail.com

**Comment by mattwynne** [comment]
@jimweirich +1 to that

**Pull request closed without merging**
