### PR TITLE
The noop refactoring should preserve indentation of well-formatted code.

### PR DESCRIPTION
**Pull request by mattwynne**
I don't think we need to worry about preserving non-conventional indentation, just put something back that looks idiomatic.

@jimweirich I think this is one for sorcerer, do you agree?

### CODE REVIEW

**Comment by bishboria** [comment]
When I was tinkering with InlineTemp using ruby_parser and Ruby2Ruby, it
seemed parentheses were added to the resultant code that didn't exist
before hand.

Do we care about that? I know those gems are no longer being used so it
might not apply now.

Cheers,
Stuart

On 3 July 2012 15:02, Matt Wynne <
reply@reply.github.com

**Comment by chrismdp** [comment]
Personally, I'd prefer to reformat indentation but keep parentheses intact. Not sure if parentheses are preserved in the sexp though.

## 

Chris Parsons
http://twitter.com/chrismdp
http://pa.rsons.org
(from my phone)

**Comment by mattwynne** [comment]
Judging by that spec, it looks like sourcerer leaves parentheses (sorry I still haven't learned not to call them brackets sometimes) intact.

This noop is really interesting. I feel like we can't go much further with the rest of it until this is working as we'd expect.

**Comment by mattwynne** [comment]
Okay since Jim says we're not going to get indentation for the time being, I'm closing this. I'll merge in the noop refactoring because it's still useful for understanding how the Ripper / Sourcer pipeline work.

**Pull request merged**
