### PR TITLE
Command-line interface

### PR DESCRIPTION
**Pull request by mattwynne**
I'm opening up this PR to start a discussion about the CLI, so we can get this thing to the point where we can start manually testing it.

The interesting it's already raised a couple of questions for me about how we communicate scope to Raffle.

I'm thinking that the most common syntax for the command is going to be:

```
raffle <refactoring> <file>[:<position>] [other args]
```

I'm imagining that an editor plugin will mostly not want to have to ask you for the name of the temp you want to remove, it just wants to know where your cursor is, and let us figure out what you probably want to do.

I've added a failing scenario for this. WDYT?

### CODE REVIEW

**Comment by tooky** [comment]
> I'm imagining that an editor plugin will mostly not want to have to ask you for the name of the temp you want to remove, it just wants to know where your cursor is, and let us figure out what you probably want to do.

At the level of editor integration, I think line and column of start and end of a selection will work? This would allow for the 'extract' refactorings. The tool probably needs to grab that selection from the file before we extract the s-expr, as the line/column numbers aren't included for everything in the ripper output.

**Comment by mattwynne** [comment]
On 9 Jul 2012, at 09:50, Steve Tooke wrote:

> At the level of editor integration, I think line and column of start and end of a selection will work? This would allow for the 'extract' refactorings.

That makes sense. But we don't always need to know an end point, so I think that should be optional.

So we could have a location indicator that's formatted like:

```
<file>:<start position>[-<end position>]
```

Where a position is:

```
<line>[,<column>]
```

e.g. foo/bar.rb:1,3-4,5

WDYT?

**Comment by mattwynne** [comment]
I'd like to see one or two end-to-end scenarios for each refactoring. I think it will help us to understand how we really want to communicate scope when we ask for these refactorings from a client tool.

**Comment by jimweirich** [comment]
Looking this over.  I like the position and range arguments.

I also think the refactoring engine should put out a list of diffs and let the editor apply the diffs.  This allows the editor to be in charge of changes and would allow it to keep the changes in the undo list.  I prefer this over having the refactoring engine modify the files directly.

Thoughts.

**Comment by jimweirich** [comment]
Some questions ... Given

```
<line>[,<column>]
```

Do line numbers start with 1?  Do column numbers start with 1 as well, or 0?

Given:

```
<file>:<start position>[-<end position>]
```

Is the end position included in the range or is it outside the range?

My suggestions:

(1) Line numbers start with 1.  I think that is common in editors
(2) Column numbers start with 0
(3) The end position is included in the range.

(2) and (3) mean that we can say line[start_pos..end_pos] in Ruby without worrying about adjusting the offsets.

**Comment by mattwynne** [comment]
On 11 Jul 2012, at 15:53, Jim Weirich wrote:

> I also think the refactoring engine should put out a list of diffs and let the editor apply the diffs.  This allows the editor to be in charge of changes and would allow it to keep the changes in the undo list.  I prefer this over having the refactoring engine modify the files directly.

I agree re the diffs. Trying out the `bin/raffle` command in this branch manually, it made me pretty nervous having the files modified for me. I think a lighter touch will be better, though it does add an extra layer of complexity for us: can we generate the diffs from a Ruby library? If not, can we assume the user has a diff tool installed? Can we bundle one inside our gem?

**Comment by tooky** [comment]
> My suggestions:
> 
> (1) Line numbers start with 1. I think that is common in editors
> (2) Column numbers start with 0
> (3) The end position is included in the range.

Ripper gives us [line,column] using 1-based index for lines and 0 based index for columns. As we need to match against that it seems a reasonable convention to stick to.

So for my part I would say yes to (1), (2) and (3).

**Comment by kevinrutherford** [comment]
I think I'd like the diffs to be a wrapper. I think we need a core refactoring engine that can (and does) modify sexps, because that feels somehow more "native". The CLI and the diffs are then adapters that connect that core capability to external tools.

**Comment by jimweirich** [comment]
On Jul 11, 2012, at 4:11 PM, Kevin Rutherford wrote:

> I think I'd like the diffs to be a wrapper. I think we need a core refactoring engine that can (and does) modify sexps, because that feels somehow more "native". The CLI and the diffs are then adapters that connect that core capability to external tools.

Yes. I agree.  I was just speaking of the command line interface.

## 

-- Jim Weirich
-- jim.weirich@gmail.com

**Comment by mattwynne** [comment]
@kevinrutherford are you suggesting they go into a different gem?

**Comment by kevinrutherford** [comment]
Er, I hadn't thought that far!  I've always regretted not splitting reek into smaller gems. I think it helps keep the architecture "clean", so I definitely wouldn't be agin it...

**Comment by mattwynne** [comment]
I've updated the code so that the feature hits RenameTemp which is our best refactoring. 

Still to do:
- remove the need to pass in original_name (figure it out from the position instead)
- generate diffs instead of modifying files

**Comment by mattwynne** [comment]
Can someone have a play with https://github.com/halostatue/diff-lcs and see if it's any use?

**Comment by chrismdp** [comment]
@mattwynne I'm not sure diff-lcs is any good. It doesn't return "normal" diff output and the code isn't quite what we need.

Given this, I vote for the original plan of outputting single files (but not changing them in place).

**Comment by mattwynne** [comment]
For the time being we're only working with single files, so @jimweirich how about we say the interface is that the refactored file contents are piped to stdout? We can cross the multiple-file bridge when we come to it.

**Comment by jimweirich** [comment]
On Jul 13, 2012, at 8:50 AM, Matt Wynne wrote:

> For the time being we're only working with single files, so @jimweirich how about we say the interface is that the refactored file contents are piped to stdout? We can cross the multiple-file bridge when we come to it.

The only problem I have with this is that Sorcerer doesn't exactly reproduce the original source (comments are lost, whitespace is different). So I am hesitant to replace the entire file with the output.  I would like to limit the replaced code to only that which really changed.  Perhaps we don't need a full diff, but just the lines to be replaced and the code that replaces it.

## 

-- Jim Weirich
-- jim.weirich@gmail.com

**Comment by mattwynne** [comment]
@jimweirich given the whitespace and comments changes, it's going to be difficult to automatically judge which lines have changed anyway then though isn't it? Or were you thinking we could construct a diff by hand, given our knowledge of which bits of the file we've been fiddling with?

**Comment by mwilden** [comment]
I disagree with producing diffs. I've never heard of a program intended to transform its input which does so by producing diffs. I imagine they exist, but it's hardly the simplest thing that could work. Just change the input into the output like anyone would expect, and would desire 97% of the time, and let git be your undo engine. You probably don't want to partially undo a refactoring anyway.

The tool should not depend on the presence of an editor, it seems to me. That's why I would pass an offset to it, rather than a line/column, which is an editor concept (I.e. can have different interpretations depending on the editor).

**Comment by mattwynne** [comment]
@mwilden what do you mean by an offset?

**Comment by mwilden** [comment]
I meant a byte or character offset from the start of the file, rather than a line number plus a column number. What is a column? If it's the byte or character offset from the start of the line, that doesn't help human users much. And if it's a visual column, then it makes no sense to a CLI.

**Comment by chrismdp** [comment]
Any reason this can't go up to master as is, in order to enable other work to be done in parallel? If we want to move to an offset we can do that in a separate request.

**Comment by mwilden** [comment]
Don't mind me (seriously). This looks like a very worthwhile project.

**Comment by chrismdp** [comment]
@mwilden :) thanks for your input: appreciated! If this branch gets too much longer though we'll end up with merge nightmares!

**Comment by mattwynne** [comment]
Let's deal with the diff output in a separate ticket. @mwilden's right that modifying the files is the simplest thing that works.

**Comment by mwilden** [comment]
Thinking about the original refactoring browser makes me wonder if even the -concept- of files should be avoided as much as possible. In Smalltalk, you run a refactoring on an image, not a collection of files. It seems to me that this tool must do the same - replacing "image" with "project directory structure". So that means that the tool not only has to know the name of the file, but also the root of the project.
(Sorry if this has already been discussed and decided, in a more appropriate place.)

**Comment by chrismdp** [comment]
Hasn't been decided yet, although we have discussed it. Multiple file refactorings are definitely on the cards, probably down the road a little bit when we better understand how to do small refactorings.

Thinking about whether we can just infer the project structure from the directory where raffle is run...

**Comment by mattwynne** [comment]
On 16 Jul 2012, at 02:01, Mark Wilden wrote:

> Thinking about the original refactoring browser makes me wonder if even the -concept- of files should be avoided as much as possible. In Smalltalk, you run a refactoring on an image, not a collection of files. It seems to me that this tool must do the same - replacing "image" with "project directory structure". So that means that the tool not only has to know the name of the file, but also the root of the project.
> (Sorry if this has already been discussed and decided, in a more appropriate place.)

I think this is one of the good arguments for using diffs, because if we need to work on multiple files, a diff is a good way to communicate those changes (without actually making them). For the time being though, we've got enough challenges just figuring out how to refactor a single snippet of Ruby code (whether it's from a file or not) so I don't want to worry about this just yet.

Thanks for bringing it up though, it's great to have more people's perspectives.

**Pull request merged**
